
package com.puntersouthall.webservice.alfresco;

import com.microsoft.schemas._2003._10.serialization.arrays.ArrayOfstring;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IPunterSouthallService", targetNamespace = "http://puntersouthall.com/webservice/alfresco/")
@XmlSeeAlso({
    com.microsoft.schemas._2003._10.serialization.ObjectFactory.class,
    com.microsoft.schemas._2003._10.serialization.arrays.ObjectFactory.class,
    ObjectFactory.class
})
public interface IPunterSouthallService {


    /**
     * 
     * @param ctnType
     * @return
     *     returns java.lang.Integer
     */
    @WebMethod(operationName = "GetCreateTaskNumber", action = "http://puntersouthall.com/webservice/alfresco/IPunterSouthallService/GetCreateTaskNumber")
    @WebResult(name = "GetCreateTaskNumberResult", targetNamespace = "http://puntersouthall.com/webservice/alfresco/")
    @RequestWrapper(localName = "GetCreateTaskNumber", targetNamespace = "http://puntersouthall.com/webservice/alfresco/", className = "com.puntersouthall.webservice.alfresco.GetCreateTaskNumber")
    @ResponseWrapper(localName = "GetCreateTaskNumberResponse", targetNamespace = "http://puntersouthall.com/webservice/alfresco/", className = "com.puntersouthall.webservice.alfresco.GetCreateTaskNumberResponse")
    public Integer getCreateTaskNumber(
            @WebParam(name = "ctnType", targetNamespace = "http://puntersouthall.com/webservice/alfresco/")
                    CreateTaskNumberType ctnType);

    /**
     * 
     * @param ctnType
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "GetChangeTaskNumber", action = "http://puntersouthall.com/webservice/alfresco/IPunterSouthallService/GetChangeTaskNumber")
    @WebResult(name = "GetChangeTaskNumberResult", targetNamespace = "http://puntersouthall.com/webservice/alfresco/")
    @RequestWrapper(localName = "GetChangeTaskNumber", targetNamespace = "http://puntersouthall.com/webservice/alfresco/", className = "com.puntersouthall.webservice.alfresco.GetChangeTaskNumber")
    @ResponseWrapper(localName = "GetChangeTaskNumberResponse", targetNamespace = "http://puntersouthall.com/webservice/alfresco/", className = "com.puntersouthall.webservice.alfresco.GetChangeTaskNumberResponse")
    public Boolean getChangeTaskNumber(
            @WebParam(name = "ctnType", targetNamespace = "http://puntersouthall.com/webservice/alfresco/")
                    ChangeTaskNumberType ctnType);

    /**
     * 
     * @param getDeadlineTypeString
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetMemberDeadline", action = "http://puntersouthall.com/webservice/alfresco/IPunterSouthallService/GetMemberDeadline")
    @WebResult(name = "GetMemberDeadlineResult", targetNamespace = "http://puntersouthall.com/webservice/alfresco/")
    @RequestWrapper(localName = "GetMemberDeadline", targetNamespace = "http://puntersouthall.com/webservice/alfresco/", className = "com.puntersouthall.webservice.alfresco.GetMemberDeadline")
    @ResponseWrapper(localName = "GetMemberDeadlineResponse", targetNamespace = "http://puntersouthall.com/webservice/alfresco/", className = "com.puntersouthall.webservice.alfresco.GetMemberDeadlineResponse")
    public String getMemberDeadline(
            @WebParam(name = "getDeadlineTypeString", targetNamespace = "http://puntersouthall.com/webservice/alfresco/")
                    String getDeadlineTypeString);

    /**
     * 
     * @param getDeadlineTypeString
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetDeadline", action = "http://puntersouthall.com/webservice/alfresco/IPunterSouthallService/GetDeadline")
    @WebResult(name = "GetDeadlineResult", targetNamespace = "http://puntersouthall.com/webservice/alfresco/")
    @RequestWrapper(localName = "GetDeadline", targetNamespace = "http://puntersouthall.com/webservice/alfresco/", className = "com.puntersouthall.webservice.alfresco.GetDeadline")
    @ResponseWrapper(localName = "GetDeadlineResponse", targetNamespace = "http://puntersouthall.com/webservice/alfresco/", className = "com.puntersouthall.webservice.alfresco.GetDeadlineResponse")
    public String getDeadline(
            @WebParam(name = "getDeadlineTypeString", targetNamespace = "http://puntersouthall.com/webservice/alfresco/")
                    String getDeadlineTypeString);

    /**
     * 
     * @param taskNumber
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "GetLogOffTask", action = "http://puntersouthall.com/webservice/alfresco/IPunterSouthallService/GetLogOffTask")
    @WebResult(name = "GetLogOffTaskResult", targetNamespace = "http://puntersouthall.com/webservice/alfresco/")
    @RequestWrapper(localName = "GetLogOffTask", targetNamespace = "http://puntersouthall.com/webservice/alfresco/", className = "com.puntersouthall.webservice.alfresco.GetLogOffTask")
    @ResponseWrapper(localName = "GetLogOffTaskResponse", targetNamespace = "http://puntersouthall.com/webservice/alfresco/", className = "com.puntersouthall.webservice.alfresco.GetLogOffTaskResponse")
    public Boolean getLogOffTask(
            @WebParam(name = "taskNumber", targetNamespace = "http://puntersouthall.com/webservice/alfresco/")
                    Integer taskNumber);

    /**
     * 
     * @return
     *     returns com.microsoft.schemas._2003._10.serialization.arrays.ArrayOfstring
     */
    @WebMethod(operationName = "GetActivities", action = "http://puntersouthall.com/webservice/alfresco/IPunterSouthallService/GetActivities")
    @WebResult(name = "GetActivitiesResult", targetNamespace = "http://puntersouthall.com/webservice/alfresco/")
    @RequestWrapper(localName = "GetActivities", targetNamespace = "http://puntersouthall.com/webservice/alfresco/", className = "com.puntersouthall.webservice.alfresco.GetActivities")
    @ResponseWrapper(localName = "GetActivitiesResponse", targetNamespace = "http://puntersouthall.com/webservice/alfresco/", className = "com.puntersouthall.webservice.alfresco.GetActivitiesResponse")
    public ArrayOfstring getActivities();

    /**
     * 
     * @param schemeName
     * @return
     *     returns com.microsoft.schemas._2003._10.serialization.arrays.ArrayOfstring
     */
    @WebMethod(operationName = "GetActivitiesForSchemeName", action = "http://puntersouthall.com/webservice/alfresco/IPunterSouthallService/GetActivitiesForSchemeName")
    @WebResult(name = "GetActivitiesForSchemeNameResult", targetNamespace = "http://puntersouthall.com/webservice/alfresco/")
    @RequestWrapper(localName = "GetActivitiesForSchemeName", targetNamespace = "http://puntersouthall.com/webservice/alfresco/", className = "com.puntersouthall.webservice.alfresco.GetActivitiesForSchemeName")
    @ResponseWrapper(localName = "GetActivitiesForSchemeNameResponse", targetNamespace = "http://puntersouthall.com/webservice/alfresco/", className = "com.puntersouthall.webservice.alfresco.GetActivitiesForSchemeNameResponse")
    public ArrayOfstring getActivitiesForSchemeName(
            @WebParam(name = "schemeName", targetNamespace = "http://puntersouthall.com/webservice/alfresco/")
                    String schemeName);

    /**
     * 
     * @return
     *     returns com.microsoft.schemas._2003._10.serialization.arrays.ArrayOfstring
     */
    @WebMethod(operationName = "GetAdminMemberActivities", action = "http://puntersouthall.com/webservice/alfresco/IPunterSouthallService/GetAdminMemberActivities")
    @WebResult(name = "GetAdminMemberActivitiesResult", targetNamespace = "http://puntersouthall.com/webservice/alfresco/")
    @RequestWrapper(localName = "GetAdminMemberActivities", targetNamespace = "http://puntersouthall.com/webservice/alfresco/", className = "com.puntersouthall.webservice.alfresco.GetAdminMemberActivities")
    @ResponseWrapper(localName = "GetAdminMemberActivitiesResponse", targetNamespace = "http://puntersouthall.com/webservice/alfresco/", className = "com.puntersouthall.webservice.alfresco.GetAdminMemberActivitiesResponse")
    public ArrayOfstring getAdminMemberActivities();

    /**
     * 
     * @param schemeName
     * @return
     *     returns com.microsoft.schemas._2003._10.serialization.arrays.ArrayOfstring
     */
    @WebMethod(operationName = "GetAdminMemberActivitiesForSchemeName", action = "http://puntersouthall.com/webservice/alfresco/IPunterSouthallService/GetAdminMemberActivitiesForSchemeName")
    @WebResult(name = "GetAdminMemberActivitiesForSchemeNameResult", targetNamespace = "http://puntersouthall.com/webservice/alfresco/")
    @RequestWrapper(localName = "GetAdminMemberActivitiesForSchemeName", targetNamespace = "http://puntersouthall.com/webservice/alfresco/", className = "com.puntersouthall.webservice.alfresco.GetAdminMemberActivitiesForSchemeName")
    @ResponseWrapper(localName = "GetAdminMemberActivitiesForSchemeNameResponse", targetNamespace = "http://puntersouthall.com/webservice/alfresco/", className = "com.puntersouthall.webservice.alfresco.GetAdminMemberActivitiesForSchemeNameResponse")
    public ArrayOfstring getAdminMemberActivitiesForSchemeName(
            @WebParam(name = "schemeName", targetNamespace = "http://puntersouthall.com/webservice/alfresco/")
                    String schemeName);

    /**
     * 
     * @return
     *     returns com.microsoft.schemas._2003._10.serialization.arrays.ArrayOfstring
     */
    @WebMethod(operationName = "GetAdminSchemeActivities", action = "http://puntersouthall.com/webservice/alfresco/IPunterSouthallService/GetAdminSchemeActivities")
    @WebResult(name = "GetAdminSchemeActivitiesResult", targetNamespace = "http://puntersouthall.com/webservice/alfresco/")
    @RequestWrapper(localName = "GetAdminSchemeActivities", targetNamespace = "http://puntersouthall.com/webservice/alfresco/", className = "com.puntersouthall.webservice.alfresco.GetAdminSchemeActivities")
    @ResponseWrapper(localName = "GetAdminSchemeActivitiesResponse", targetNamespace = "http://puntersouthall.com/webservice/alfresco/", className = "com.puntersouthall.webservice.alfresco.GetAdminSchemeActivitiesResponse")
    public ArrayOfstring getAdminSchemeActivities();

    /**
     * 
     * @param schemeName
     * @return
     *     returns com.microsoft.schemas._2003._10.serialization.arrays.ArrayOfstring
     */
    @WebMethod(operationName = "GetAdminSchemeActivitiesForSchemeName", action = "http://puntersouthall.com/webservice/alfresco/IPunterSouthallService/GetAdminSchemeActivitiesForSchemeName")
    @WebResult(name = "GetAdminSchemeActivitiesForSchemeNameResult", targetNamespace = "http://puntersouthall.com/webservice/alfresco/")
    @RequestWrapper(localName = "GetAdminSchemeActivitiesForSchemeName", targetNamespace = "http://puntersouthall.com/webservice/alfresco/", className = "com.puntersouthall.webservice.alfresco.GetAdminSchemeActivitiesForSchemeName")
    @ResponseWrapper(localName = "GetAdminSchemeActivitiesForSchemeNameResponse", targetNamespace = "http://puntersouthall.com/webservice/alfresco/", className = "com.puntersouthall.webservice.alfresco.GetAdminSchemeActivitiesForSchemeNameResponse")
    public ArrayOfstring getAdminSchemeActivitiesForSchemeName(
            @WebParam(name = "schemeName", targetNamespace = "http://puntersouthall.com/webservice/alfresco/")
                    String schemeName);

    /**
     * 
     * @return
     *     returns com.microsoft.schemas._2003._10.serialization.arrays.ArrayOfstring
     */
    @WebMethod(operationName = "GetPayrollActivities", action = "http://puntersouthall.com/webservice/alfresco/IPunterSouthallService/GetPayrollActivities")
    @WebResult(name = "GetPayrollActivitiesResult", targetNamespace = "http://puntersouthall.com/webservice/alfresco/")
    @RequestWrapper(localName = "GetPayrollActivities", targetNamespace = "http://puntersouthall.com/webservice/alfresco/", className = "com.puntersouthall.webservice.alfresco.GetPayrollActivities")
    @ResponseWrapper(localName = "GetPayrollActivitiesResponse", targetNamespace = "http://puntersouthall.com/webservice/alfresco/", className = "com.puntersouthall.webservice.alfresco.GetPayrollActivitiesResponse")
    public ArrayOfstring getPayrollActivities();

    /**
     * 
     * @param schemeName
     * @return
     *     returns com.microsoft.schemas._2003._10.serialization.arrays.ArrayOfstring
     */
    @WebMethod(operationName = "GetPayrollActivitiesForSchemeName", action = "http://puntersouthall.com/webservice/alfresco/IPunterSouthallService/GetPayrollActivitiesForSchemeName")
    @WebResult(name = "GetPayrollActivitiesForSchemeNameResult", targetNamespace = "http://puntersouthall.com/webservice/alfresco/")
    @RequestWrapper(localName = "GetPayrollActivitiesForSchemeName", targetNamespace = "http://puntersouthall.com/webservice/alfresco/", className = "com.puntersouthall.webservice.alfresco.GetPayrollActivitiesForSchemeName")
    @ResponseWrapper(localName = "GetPayrollActivitiesForSchemeNameResponse", targetNamespace = "http://puntersouthall.com/webservice/alfresco/", className = "com.puntersouthall.webservice.alfresco.GetPayrollActivitiesForSchemeNameResponse")
    public ArrayOfstring getPayrollActivitiesForSchemeName(
            @WebParam(name = "schemeName", targetNamespace = "http://puntersouthall.com/webservice/alfresco/")
                    String schemeName);

    /**
     * 
     * @param activity
     * @return
     *     returns com.microsoft.schemas._2003._10.serialization.arrays.ArrayOfstring
     */
    @WebMethod(operationName = "GetSubActivitiesForMemberActivity", action = "http://puntersouthall.com/webservice/alfresco/IPunterSouthallService/GetSubActivitiesForMemberActivity")
    @WebResult(name = "GetSubActivitiesForMemberActivityResult", targetNamespace = "http://puntersouthall.com/webservice/alfresco/")
    @RequestWrapper(localName = "GetSubActivitiesForMemberActivity", targetNamespace = "http://puntersouthall.com/webservice/alfresco/", className = "com.puntersouthall.webservice.alfresco.GetSubActivitiesForMemberActivity")
    @ResponseWrapper(localName = "GetSubActivitiesForMemberActivityResponse", targetNamespace = "http://puntersouthall.com/webservice/alfresco/", className = "com.puntersouthall.webservice.alfresco.GetSubActivitiesForMemberActivityResponse")
    public ArrayOfstring getSubActivitiesForMemberActivity(
            @WebParam(name = "activity", targetNamespace = "http://puntersouthall.com/webservice/alfresco/")
                    String activity);

    /**
     * 
     * @param activity
     * @return
     *     returns com.microsoft.schemas._2003._10.serialization.arrays.ArrayOfstring
     */
    @WebMethod(operationName = "GetSubActivitiesForActivity", action = "http://puntersouthall.com/webservice/alfresco/IPunterSouthallService/GetSubActivitiesForActivity")
    @WebResult(name = "GetSubActivitiesForActivityResult", targetNamespace = "http://puntersouthall.com/webservice/alfresco/")
    @RequestWrapper(localName = "GetSubActivitiesForActivity", targetNamespace = "http://puntersouthall.com/webservice/alfresco/", className = "com.puntersouthall.webservice.alfresco.GetSubActivitiesForActivity")
    @ResponseWrapper(localName = "GetSubActivitiesForActivityResponse", targetNamespace = "http://puntersouthall.com/webservice/alfresco/", className = "com.puntersouthall.webservice.alfresco.GetSubActivitiesForActivityResponse")
    public ArrayOfstring getSubActivitiesForActivity(
            @WebParam(name = "activity", targetNamespace = "http://puntersouthall.com/webservice/alfresco/")
                    String activity);

    /**
     * 
     * @return
     *     returns com.microsoft.schemas._2003._10.serialization.arrays.ArrayOfstring
     */
    @WebMethod(operationName = "GetAdminMemberDocumentTypes", action = "http://puntersouthall.com/webservice/alfresco/IPunterSouthallService/GetAdminMemberDocumentTypes")
    @WebResult(name = "GetAdminMemberDocumentTypesResult", targetNamespace = "http://puntersouthall.com/webservice/alfresco/")
    @RequestWrapper(localName = "GetAdminMemberDocumentTypes", targetNamespace = "http://puntersouthall.com/webservice/alfresco/", className = "com.puntersouthall.webservice.alfresco.GetAdminMemberDocumentTypes")
    @ResponseWrapper(localName = "GetAdminMemberDocumentTypesResponse", targetNamespace = "http://puntersouthall.com/webservice/alfresco/", className = "com.puntersouthall.webservice.alfresco.GetAdminMemberDocumentTypesResponse")
    public ArrayOfstring getAdminMemberDocumentTypes();

    /**
     * 
     * @return
     *     returns com.microsoft.schemas._2003._10.serialization.arrays.ArrayOfstring
     */
    @WebMethod(operationName = "GetAdminSchemeDocumentTypes", action = "http://puntersouthall.com/webservice/alfresco/IPunterSouthallService/GetAdminSchemeDocumentTypes")
    @WebResult(name = "GetAdminSchemeDocumentTypesResult", targetNamespace = "http://puntersouthall.com/webservice/alfresco/")
    @RequestWrapper(localName = "GetAdminSchemeDocumentTypes", targetNamespace = "http://puntersouthall.com/webservice/alfresco/", className = "com.puntersouthall.webservice.alfresco.GetAdminSchemeDocumentTypes")
    @ResponseWrapper(localName = "GetAdminSchemeDocumentTypesResponse", targetNamespace = "http://puntersouthall.com/webservice/alfresco/", className = "com.puntersouthall.webservice.alfresco.GetAdminSchemeDocumentTypesResponse")
    public ArrayOfstring getAdminSchemeDocumentTypes();

    /**
     * 
     * @return
     *     returns com.microsoft.schemas._2003._10.serialization.arrays.ArrayOfstring
     */
    @WebMethod(operationName = "GetAdminSchemeControlDocumentTypes", action = "http://puntersouthall.com/webservice/alfresco/IPunterSouthallService/GetAdminSchemeControlDocumentTypes")
    @WebResult(name = "GetAdminSchemeControlDocumentTypesResult", targetNamespace = "http://puntersouthall.com/webservice/alfresco/")
    @RequestWrapper(localName = "GetAdminSchemeControlDocumentTypes", targetNamespace = "http://puntersouthall.com/webservice/alfresco/", className = "com.puntersouthall.webservice.alfresco.GetAdminSchemeControlDocumentTypes")
    @ResponseWrapper(localName = "GetAdminSchemeControlDocumentTypesResponse", targetNamespace = "http://puntersouthall.com/webservice/alfresco/", className = "com.puntersouthall.webservice.alfresco.GetAdminSchemeControlDocumentTypesResponse")
    public ArrayOfstring getAdminSchemeControlDocumentTypes();

    /**
     * 
     * @return
     *     returns com.microsoft.schemas._2003._10.serialization.arrays.ArrayOfstring
     */
    @WebMethod(operationName = "GetCashieringDocumentTypes", action = "http://puntersouthall.com/webservice/alfresco/IPunterSouthallService/GetCashieringDocumentTypes")
    @WebResult(name = "GetCashieringDocumentTypesResult", targetNamespace = "http://puntersouthall.com/webservice/alfresco/")
    @RequestWrapper(localName = "GetCashieringDocumentTypes", targetNamespace = "http://puntersouthall.com/webservice/alfresco/", className = "com.puntersouthall.webservice.alfresco.GetCashieringDocumentTypes")
    @ResponseWrapper(localName = "GetCashieringDocumentTypesResponse", targetNamespace = "http://puntersouthall.com/webservice/alfresco/", className = "com.puntersouthall.webservice.alfresco.GetCashieringDocumentTypesResponse")
    public ArrayOfstring getCashieringDocumentTypes();

    /**
     * 
     * @param cashieringDocumentType
     * @return
     *     returns com.microsoft.schemas._2003._10.serialization.arrays.ArrayOfstring
     */
    @WebMethod(operationName = "GetCashieringPaymentTypes", action = "http://puntersouthall.com/webservice/alfresco/IPunterSouthallService/GetCashieringPaymentTypes")
    @WebResult(name = "GetCashieringPaymentTypesResult", targetNamespace = "http://puntersouthall.com/webservice/alfresco/")
    @RequestWrapper(localName = "GetCashieringPaymentTypes", targetNamespace = "http://puntersouthall.com/webservice/alfresco/", className = "com.puntersouthall.webservice.alfresco.GetCashieringPaymentTypes")
    @ResponseWrapper(localName = "GetCashieringPaymentTypesResponse", targetNamespace = "http://puntersouthall.com/webservice/alfresco/", className = "com.puntersouthall.webservice.alfresco.GetCashieringPaymentTypesResponse")
    public ArrayOfstring getCashieringPaymentTypes(
            @WebParam(name = "cashieringDocumentType", targetNamespace = "http://puntersouthall.com/webservice/alfresco/")
                    String cashieringDocumentType);

    /**
     * 
     * @return
     *     returns com.microsoft.schemas._2003._10.serialization.arrays.ArrayOfstring
     */
    @WebMethod(operationName = "GetWebDocumentTypes", action = "http://puntersouthall.com/webservice/alfresco/IPunterSouthallService/GetWebDocumentTypes")
    @WebResult(name = "GetWebDocumentTypesResult", targetNamespace = "http://puntersouthall.com/webservice/alfresco/")
    @RequestWrapper(localName = "GetWebDocumentTypes", targetNamespace = "http://puntersouthall.com/webservice/alfresco/", className = "com.puntersouthall.webservice.alfresco.GetWebDocumentTypes")
    @ResponseWrapper(localName = "GetWebDocumentTypesResponse", targetNamespace = "http://puntersouthall.com/webservice/alfresco/", className = "com.puntersouthall.webservice.alfresco.GetWebDocumentTypesResponse")
    public ArrayOfstring getWebDocumentTypes();

    /**
     * 
     * @param memberTypeString
     * @return
     *     returns com.puntersouthall.webservice.alfresco.ArrayOfMemberType
     */
    @WebMethod(operationName = "GetMemberDetails", action = "http://puntersouthall.com/webservice/alfresco/IPunterSouthallService/GetMemberDetails")
    @WebResult(name = "GetMemberDetailsResult", targetNamespace = "http://puntersouthall.com/webservice/alfresco/")
    @RequestWrapper(localName = "GetMemberDetails", targetNamespace = "http://puntersouthall.com/webservice/alfresco/", className = "com.puntersouthall.webservice.alfresco.GetMemberDetails")
    @ResponseWrapper(localName = "GetMemberDetailsResponse", targetNamespace = "http://puntersouthall.com/webservice/alfresco/", className = "com.puntersouthall.webservice.alfresco.GetMemberDetailsResponse")
    public ArrayOfMemberType getMemberDetails(
            @WebParam(name = "memberTypeString", targetNamespace = "http://puntersouthall.com/webservice/alfresco/")
                    String memberTypeString);

    /**
     * 
     * @param memberTypeString
     * @return
     *     returns com.puntersouthall.webservice.alfresco.ArrayOfMemberType
     */
    @WebMethod(operationName = "GetPersonDetails", action = "http://puntersouthall.com/webservice/alfresco/IPunterSouthallService/GetPersonDetails")
    @WebResult(name = "GetPersonDetailsResult", targetNamespace = "http://puntersouthall.com/webservice/alfresco/")
    @RequestWrapper(localName = "GetPersonDetails", targetNamespace = "http://puntersouthall.com/webservice/alfresco/", className = "com.puntersouthall.webservice.alfresco.GetPersonDetails")
    @ResponseWrapper(localName = "GetPersonDetailsResponse", targetNamespace = "http://puntersouthall.com/webservice/alfresco/", className = "com.puntersouthall.webservice.alfresco.GetPersonDetailsResponse")
    public ArrayOfMemberType getPersonDetails(
            @WebParam(name = "memberTypeString", targetNamespace = "http://puntersouthall.com/webservice/alfresco/")
                    String memberTypeString);

    /**
     * 
     * @param schemeTypeString
     * @return
     *     returns com.puntersouthall.webservice.alfresco.ArrayOfSchemeType
     */
    @WebMethod(operationName = "GetSchemeDetails", action = "http://puntersouthall.com/webservice/alfresco/IPunterSouthallService/GetSchemeDetails")
    @WebResult(name = "GetSchemeDetailsResult", targetNamespace = "http://puntersouthall.com/webservice/alfresco/")
    @RequestWrapper(localName = "GetSchemeDetails", targetNamespace = "http://puntersouthall.com/webservice/alfresco/", className = "com.puntersouthall.webservice.alfresco.GetSchemeDetails")
    @ResponseWrapper(localName = "GetSchemeDetailsResponse", targetNamespace = "http://puntersouthall.com/webservice/alfresco/", className = "com.puntersouthall.webservice.alfresco.GetSchemeDetailsResponse")
    public ArrayOfSchemeType getSchemeDetails(
            @WebParam(name = "schemeTypeString", targetNamespace = "http://puntersouthall.com/webservice/alfresco/")
                    String schemeTypeString);

    /**
     * 
     * @return
     *     returns com.puntersouthall.webservice.alfresco.ArrayOfClientType
     */
    @WebMethod(operationName = "GetClientNames", action = "http://puntersouthall.com/webservice/alfresco/IPunterSouthallService/GetClientNames")
    @WebResult(name = "GetClientNamesResult", targetNamespace = "http://puntersouthall.com/webservice/alfresco/")
    @RequestWrapper(localName = "GetClientNames", targetNamespace = "http://puntersouthall.com/webservice/alfresco/", className = "com.puntersouthall.webservice.alfresco.GetClientNames")
    @ResponseWrapper(localName = "GetClientNamesResponse", targetNamespace = "http://puntersouthall.com/webservice/alfresco/", className = "com.puntersouthall.webservice.alfresco.GetClientNamesResponse")
    public ArrayOfClientType getClientNames();

    /**
     * 
     * @param schemeType
     * @param clientName
     * @return
     *     returns com.puntersouthall.webservice.alfresco.ArrayOfSchemeType
     */
    @WebMethod(operationName = "GetSchemeNamesForClient", action = "http://puntersouthall.com/webservice/alfresco/IPunterSouthallService/GetSchemeNamesForClient")
    @WebResult(name = "GetSchemeNamesForClientResult", targetNamespace = "http://puntersouthall.com/webservice/alfresco/")
    @RequestWrapper(localName = "GetSchemeNamesForClient", targetNamespace = "http://puntersouthall.com/webservice/alfresco/", className = "com.puntersouthall.webservice.alfresco.GetSchemeNamesForClient")
    @ResponseWrapper(localName = "GetSchemeNamesForClientResponse", targetNamespace = "http://puntersouthall.com/webservice/alfresco/", className = "com.puntersouthall.webservice.alfresco.GetSchemeNamesForClientResponse")
    public ArrayOfSchemeType getSchemeNamesForClient(
            @WebParam(name = "clientName", targetNamespace = "http://puntersouthall.com/webservice/alfresco/")
                    String clientName,
            @WebParam(name = "schemeType", targetNamespace = "http://puntersouthall.com/webservice/alfresco/")
                    String schemeType);

    /**
     * 
     * @return
     *     returns com.puntersouthall.webservice.alfresco.ArrayOfSchemeType
     */
    @WebMethod(operationName = "GetAdminSchemeNames", action = "http://puntersouthall.com/webservice/alfresco/IPunterSouthallService/GetAdminSchemeNames")
    @WebResult(name = "GetAdminSchemeNamesResult", targetNamespace = "http://puntersouthall.com/webservice/alfresco/")
    @RequestWrapper(localName = "GetAdminSchemeNames", targetNamespace = "http://puntersouthall.com/webservice/alfresco/", className = "com.puntersouthall.webservice.alfresco.GetAdminSchemeNames")
    @ResponseWrapper(localName = "GetAdminSchemeNamesResponse", targetNamespace = "http://puntersouthall.com/webservice/alfresco/", className = "com.puntersouthall.webservice.alfresco.GetAdminSchemeNamesResponse")
    public ArrayOfSchemeType getAdminSchemeNames();

    /**
     * 
     * @return
     *     returns com.puntersouthall.webservice.alfresco.ArrayOfSchemeType
     */
    @WebMethod(operationName = "GetPayrollSchemeNames", action = "http://puntersouthall.com/webservice/alfresco/IPunterSouthallService/GetPayrollSchemeNames")
    @WebResult(name = "GetPayrollSchemeNamesResult", targetNamespace = "http://puntersouthall.com/webservice/alfresco/")
    @RequestWrapper(localName = "GetPayrollSchemeNames", targetNamespace = "http://puntersouthall.com/webservice/alfresco/", className = "com.puntersouthall.webservice.alfresco.GetPayrollSchemeNames")
    @ResponseWrapper(localName = "GetPayrollSchemeNamesResponse", targetNamespace = "http://puntersouthall.com/webservice/alfresco/", className = "com.puntersouthall.webservice.alfresco.GetPayrollSchemeNamesResponse")
    public ArrayOfSchemeType getPayrollSchemeNames();

    /**
     * 
     * @param endOfDay
     * @return
     *     returns com.puntersouthall.webservice.alfresco.ArrayOfCentralMemberRecordChangeType
     */
    @WebMethod(operationName = "GetCentralMemberRecordsChanges", action = "http://puntersouthall.com/webservice/alfresco/IPunterSouthallService/GetCentralMemberRecordsChanges")
    @WebResult(name = "GetCentralMemberRecordsChangesResult", targetNamespace = "http://puntersouthall.com/webservice/alfresco/")
    @RequestWrapper(localName = "GetCentralMemberRecordsChanges", targetNamespace = "http://puntersouthall.com/webservice/alfresco/", className = "com.puntersouthall.webservice.alfresco.GetCentralMemberRecordsChanges")
    @ResponseWrapper(localName = "GetCentralMemberRecordsChangesResponse", targetNamespace = "http://puntersouthall.com/webservice/alfresco/", className = "com.puntersouthall.webservice.alfresco.GetCentralMemberRecordsChangesResponse")
    public ArrayOfCentralMemberRecordChangeType getCentralMemberRecordsChanges(
            @WebParam(name = "endOfDay", targetNamespace = "http://puntersouthall.com/webservice/alfresco/")
                    Boolean endOfDay);

    /**
     * 
     * @param endOfDay
     * @param centralMemberRecordsChangeID
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "UpdateCentralMemberRecordsChangeRecord", action = "http://puntersouthall.com/webservice/alfresco/IPunterSouthallService/UpdateCentralMemberRecordsChangeRecord")
    @WebResult(name = "UpdateCentralMemberRecordsChangeRecordResult", targetNamespace = "http://puntersouthall.com/webservice/alfresco/")
    @RequestWrapper(localName = "UpdateCentralMemberRecordsChangeRecord", targetNamespace = "http://puntersouthall.com/webservice/alfresco/", className = "com.puntersouthall.webservice.alfresco.UpdateCentralMemberRecordsChangeRecord")
    @ResponseWrapper(localName = "UpdateCentralMemberRecordsChangeRecordResponse", targetNamespace = "http://puntersouthall.com/webservice/alfresco/", className = "com.puntersouthall.webservice.alfresco.UpdateCentralMemberRecordsChangeRecordResponse")
    public Boolean updateCentralMemberRecordsChangeRecord(
            @WebParam(name = "centralMemberRecordsChangeID", targetNamespace = "http://puntersouthall.com/webservice/alfresco/")
                    Integer centralMemberRecordsChangeID,
            @WebParam(name = "endOfDay", targetNamespace = "http://puntersouthall.com/webservice/alfresco/")
                    Boolean endOfDay);

    /**
     * 
     * @param schemeName
     * @return
     *     returns com.microsoft.schemas._2003._10.serialization.arrays.ArrayOfstring
     */
    @WebMethod(operationName = "GetTeamNameForSchemeName", action = "http://puntersouthall.com/webservice/alfresco/IPunterSouthallService/GetTeamNameForSchemeName")
    @WebResult(name = "GetTeamNameForSchemeNameResult", targetNamespace = "http://puntersouthall.com/webservice/alfresco/")
    @RequestWrapper(localName = "GetTeamNameForSchemeName", targetNamespace = "http://puntersouthall.com/webservice/alfresco/", className = "com.puntersouthall.webservice.alfresco.GetTeamNameForSchemeName")
    @ResponseWrapper(localName = "GetTeamNameForSchemeNameResponse", targetNamespace = "http://puntersouthall.com/webservice/alfresco/", className = "com.puntersouthall.webservice.alfresco.GetTeamNameForSchemeNameResponse")
    public ArrayOfstring getTeamNameForSchemeName(
            @WebParam(name = "schemeName", targetNamespace = "http://puntersouthall.com/webservice/alfresco/")
                    String schemeName);

    /**
     * 
     * @return
     *     returns com.puntersouthall.webservice.alfresco.ArrayOfAutomatedTaskType
     */
    @WebMethod(operationName = "GetAutomatedLaunchTasksForToday", action = "http://puntersouthall.com/webservice/alfresco/IPunterSouthallService/GetAutomatedLaunchTasksForToday")
    @WebResult(name = "GetAutomatedLaunchTasksForTodayResult", targetNamespace = "http://puntersouthall.com/webservice/alfresco/")
    @RequestWrapper(localName = "GetAutomatedLaunchTasksForToday", targetNamespace = "http://puntersouthall.com/webservice/alfresco/", className = "com.puntersouthall.webservice.alfresco.GetAutomatedLaunchTasksForToday")
    @ResponseWrapper(localName = "GetAutomatedLaunchTasksForTodayResponse", targetNamespace = "http://puntersouthall.com/webservice/alfresco/", className = "com.puntersouthall.webservice.alfresco.GetAutomatedLaunchTasksForTodayResponse")
    public ArrayOfAutomatedTaskType getAutomatedLaunchTasksForToday();

    /**
     * 
     * @param automatedLaunchListID
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "UpdateAutomatedTaskLaunched", action = "http://puntersouthall.com/webservice/alfresco/IPunterSouthallService/UpdateAutomatedTaskLaunched")
    @WebResult(name = "UpdateAutomatedTaskLaunchedResult", targetNamespace = "http://puntersouthall.com/webservice/alfresco/")
    @RequestWrapper(localName = "UpdateAutomatedTaskLaunched", targetNamespace = "http://puntersouthall.com/webservice/alfresco/", className = "com.puntersouthall.webservice.alfresco.UpdateAutomatedTaskLaunched")
    @ResponseWrapper(localName = "UpdateAutomatedTaskLaunchedResponse", targetNamespace = "http://puntersouthall.com/webservice/alfresco/", className = "com.puntersouthall.webservice.alfresco.UpdateAutomatedTaskLaunchedResponse")
    public Boolean updateAutomatedTaskLaunched(
            @WebParam(name = "automatedLaunchListID", targetNamespace = "http://puntersouthall.com/webservice/alfresco/")
                    Integer automatedLaunchListID);

    /**
     * 
     * @param taskNumber
     * @return
     *     returns com.puntersouthall.webservice.alfresco.ArrayOfAccuracyReturnType
     */
    @WebMethod(operationName = "GetAccuracyForTask", action = "http://puntersouthall.com/webservice/alfresco/IPunterSouthallService/GetAccuracyForTask")
    @WebResult(name = "GetAccuracyForTaskResult", targetNamespace = "http://puntersouthall.com/webservice/alfresco/")
    @RequestWrapper(localName = "GetAccuracyForTask", targetNamespace = "http://puntersouthall.com/webservice/alfresco/", className = "com.puntersouthall.webservice.alfresco.GetAccuracyForTask")
    @ResponseWrapper(localName = "GetAccuracyForTaskResponse", targetNamespace = "http://puntersouthall.com/webservice/alfresco/", className = "com.puntersouthall.webservice.alfresco.GetAccuracyForTaskResponse")
    public ArrayOfAccuracyReturnType getAccuracyForTask(
            @WebParam(name = "taskNumber", targetNamespace = "http://puntersouthall.com/webservice/alfresco/")
                    Integer taskNumber);

    /**
     * 
     * @param accuracyInsertTypeString
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "InsertAccuracyForTask", action = "http://puntersouthall.com/webservice/alfresco/IPunterSouthallService/InsertAccuracyForTask")
    @WebResult(name = "InsertAccuracyForTaskResult", targetNamespace = "http://puntersouthall.com/webservice/alfresco/")
    @RequestWrapper(localName = "InsertAccuracyForTask", targetNamespace = "http://puntersouthall.com/webservice/alfresco/", className = "com.puntersouthall.webservice.alfresco.InsertAccuracyForTask")
    @ResponseWrapper(localName = "InsertAccuracyForTaskResponse", targetNamespace = "http://puntersouthall.com/webservice/alfresco/", className = "com.puntersouthall.webservice.alfresco.InsertAccuracyForTaskResponse")
    public Boolean insertAccuracyForTask(
            @WebParam(name = "accuracyInsertTypeString", targetNamespace = "http://puntersouthall.com/webservice/alfresco/")
                    String accuracyInsertTypeString);

    /**
     * 
     * @param accuracyUpdateTypeString
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "UpdateAccuracyForTask", action = "http://puntersouthall.com/webservice/alfresco/IPunterSouthallService/UpdateAccuracyForTask")
    @WebResult(name = "UpdateAccuracyForTaskResult", targetNamespace = "http://puntersouthall.com/webservice/alfresco/")
    @RequestWrapper(localName = "UpdateAccuracyForTask", targetNamespace = "http://puntersouthall.com/webservice/alfresco/", className = "com.puntersouthall.webservice.alfresco.UpdateAccuracyForTask")
    @ResponseWrapper(localName = "UpdateAccuracyForTaskResponse", targetNamespace = "http://puntersouthall.com/webservice/alfresco/", className = "com.puntersouthall.webservice.alfresco.UpdateAccuracyForTaskResponse")
    public Boolean updateAccuracyForTask(
            @WebParam(name = "accuracyUpdateTypeString", targetNamespace = "http://puntersouthall.com/webservice/alfresco/")
                    String accuracyUpdateTypeString);

    /**
     * 
     * @param diaryNoteIndex
     * @param approvedBy
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "DiaryNoteApproveDeletion", action = "http://puntersouthall.com/webservice/alfresco/IPunterSouthallService/DiaryNoteApproveDeletion")
    @WebResult(name = "DiaryNoteApproveDeletionResult", targetNamespace = "http://puntersouthall.com/webservice/alfresco/")
    @RequestWrapper(localName = "DiaryNoteApproveDeletion", targetNamespace = "http://puntersouthall.com/webservice/alfresco/", className = "com.puntersouthall.webservice.alfresco.DiaryNoteApproveDeletion")
    @ResponseWrapper(localName = "DiaryNoteApproveDeletionResponse", targetNamespace = "http://puntersouthall.com/webservice/alfresco/", className = "com.puntersouthall.webservice.alfresco.DiaryNoteApproveDeletionResponse")
    public Boolean diaryNoteApproveDeletion(
            @WebParam(name = "diaryNoteIndex", targetNamespace = "http://puntersouthall.com/webservice/alfresco/")
                    Integer diaryNoteIndex,
            @WebParam(name = "approvedBy", targetNamespace = "http://puntersouthall.com/webservice/alfresco/")
                    String approvedBy);

    /**
     * 
     * @param diaryNoteIndex
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "DiaryNoteCancelDeletion", action = "http://puntersouthall.com/webservice/alfresco/IPunterSouthallService/DiaryNoteCancelDeletion")
    @WebResult(name = "DiaryNoteCancelDeletionResult", targetNamespace = "http://puntersouthall.com/webservice/alfresco/")
    @RequestWrapper(localName = "DiaryNoteCancelDeletion", targetNamespace = "http://puntersouthall.com/webservice/alfresco/", className = "com.puntersouthall.webservice.alfresco.DiaryNoteCancelDeletion")
    @ResponseWrapper(localName = "DiaryNoteCancelDeletionResponse", targetNamespace = "http://puntersouthall.com/webservice/alfresco/", className = "com.puntersouthall.webservice.alfresco.DiaryNoteCancelDeletionResponse")
    public Boolean diaryNoteCancelDeletion(
            @WebParam(name = "diaryNoteIndex", targetNamespace = "http://puntersouthall.com/webservice/alfresco/")
                    Integer diaryNoteIndex);

    /**
     * 
     * @param requestedBy
     * @param diaryNoteIndex
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "DiaryNoteRequestDeletion", action = "http://puntersouthall.com/webservice/alfresco/IPunterSouthallService/DiaryNoteRequestDeletion")
    @WebResult(name = "DiaryNoteRequestDeletionResult", targetNamespace = "http://puntersouthall.com/webservice/alfresco/")
    @RequestWrapper(localName = "DiaryNoteRequestDeletion", targetNamespace = "http://puntersouthall.com/webservice/alfresco/", className = "com.puntersouthall.webservice.alfresco.DiaryNoteRequestDeletion")
    @ResponseWrapper(localName = "DiaryNoteRequestDeletionResponse", targetNamespace = "http://puntersouthall.com/webservice/alfresco/", className = "com.puntersouthall.webservice.alfresco.DiaryNoteRequestDeletionResponse")
    public Boolean diaryNoteRequestDeletion(
            @WebParam(name = "diaryNoteIndex", targetNamespace = "http://puntersouthall.com/webservice/alfresco/")
                    Integer diaryNoteIndex,
            @WebParam(name = "requestedBy", targetNamespace = "http://puntersouthall.com/webservice/alfresco/")
                    String requestedBy);

    /**
     * 
     * @param diaryNoteIndex
     * @return
     *     returns com.puntersouthall.webservice.alfresco.ArrayOfDiaryNoteReturnType
     */
    @WebMethod(operationName = "GetDiaryNote", action = "http://puntersouthall.com/webservice/alfresco/IPunterSouthallService/GetDiaryNote")
    @WebResult(name = "GetDiaryNoteResult", targetNamespace = "http://puntersouthall.com/webservice/alfresco/")
    @RequestWrapper(localName = "GetDiaryNote", targetNamespace = "http://puntersouthall.com/webservice/alfresco/", className = "com.puntersouthall.webservice.alfresco.GetDiaryNote")
    @ResponseWrapper(localName = "GetDiaryNoteResponse", targetNamespace = "http://puntersouthall.com/webservice/alfresco/", className = "com.puntersouthall.webservice.alfresco.GetDiaryNoteResponse")
    public ArrayOfDiaryNoteReturnType getDiaryNote(
            @WebParam(name = "diaryNoteIndex", targetNamespace = "http://puntersouthall.com/webservice/alfresco/")
                    Integer diaryNoteIndex);

    /**
     * 
     * @param centralMemberRecordID
     * @param databaseMemberID
     * @return
     *     returns com.puntersouthall.webservice.alfresco.ArrayOfDiaryNoteReturnType
     */
    @WebMethod(operationName = "GetDiaryNotesForMember", action = "http://puntersouthall.com/webservice/alfresco/IPunterSouthallService/GetDiaryNotesForMember")
    @WebResult(name = "GetDiaryNotesForMemberResult", targetNamespace = "http://puntersouthall.com/webservice/alfresco/")
    @RequestWrapper(localName = "GetDiaryNotesForMember", targetNamespace = "http://puntersouthall.com/webservice/alfresco/", className = "com.puntersouthall.webservice.alfresco.GetDiaryNotesForMember")
    @ResponseWrapper(localName = "GetDiaryNotesForMemberResponse", targetNamespace = "http://puntersouthall.com/webservice/alfresco/", className = "com.puntersouthall.webservice.alfresco.GetDiaryNotesForMemberResponse")
    public ArrayOfDiaryNoteReturnType getDiaryNotesForMember(
            @WebParam(name = "centralMemberRecordID", targetNamespace = "http://puntersouthall.com/webservice/alfresco/")
                    Integer centralMemberRecordID,
            @WebParam(name = "databaseMemberID", targetNamespace = "http://puntersouthall.com/webservice/alfresco/")
                    Integer databaseMemberID);

    /**
     * 
     * @param activity
     * @param schemeName
     * @return
     *     returns com.puntersouthall.webservice.alfresco.ArrayOfDiaryNoteReturnType
     */
    @WebMethod(operationName = "GetDiaryNotesForSchemeActivity", action = "http://puntersouthall.com/webservice/alfresco/IPunterSouthallService/GetDiaryNotesForSchemeActivity")
    @WebResult(name = "GetDiaryNotesForSchemeActivityResult", targetNamespace = "http://puntersouthall.com/webservice/alfresco/")
    @RequestWrapper(localName = "GetDiaryNotesForSchemeActivity", targetNamespace = "http://puntersouthall.com/webservice/alfresco/", className = "com.puntersouthall.webservice.alfresco.GetDiaryNotesForSchemeActivity")
    @ResponseWrapper(localName = "GetDiaryNotesForSchemeActivityResponse", targetNamespace = "http://puntersouthall.com/webservice/alfresco/", className = "com.puntersouthall.webservice.alfresco.GetDiaryNotesForSchemeActivityResponse")
    public ArrayOfDiaryNoteReturnType getDiaryNotesForSchemeActivity(
            @WebParam(name = "schemeName", targetNamespace = "http://puntersouthall.com/webservice/alfresco/")
                    String schemeName,
            @WebParam(name = "activity", targetNamespace = "http://puntersouthall.com/webservice/alfresco/")
                    String activity);

    /**
     * 
     * @param diaryNoteInsertTypeString
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "InsertDiaryNote", action = "http://puntersouthall.com/webservice/alfresco/IPunterSouthallService/InsertDiaryNote")
    @WebResult(name = "InsertDiaryNoteResult", targetNamespace = "http://puntersouthall.com/webservice/alfresco/")
    @RequestWrapper(localName = "InsertDiaryNote", targetNamespace = "http://puntersouthall.com/webservice/alfresco/", className = "com.puntersouthall.webservice.alfresco.InsertDiaryNote")
    @ResponseWrapper(localName = "InsertDiaryNoteResponse", targetNamespace = "http://puntersouthall.com/webservice/alfresco/", className = "com.puntersouthall.webservice.alfresco.InsertDiaryNoteResponse")
    public Boolean insertDiaryNote(
            @WebParam(name = "diaryNoteInsertTypeString", targetNamespace = "http://puntersouthall.com/webservice/alfresco/")
                    String diaryNoteInsertTypeString);

    /**
     * 
     * @param centralMemberRecordID
     * @param recordsToReturn
     * @param returnAllRecords
     * @param databaseMemberID
     * @return
     *     returns com.puntersouthall.webservice.alfresco.ArrayOfRecentTasksReturnType
     */
    @WebMethod(operationName = "GetRecentTasksForMember", action = "http://puntersouthall.com/webservice/alfresco/IPunterSouthallService/GetRecentTasksForMember")
    @WebResult(name = "GetRecentTasksForMemberResult", targetNamespace = "http://puntersouthall.com/webservice/alfresco/")
    @RequestWrapper(localName = "GetRecentTasksForMember", targetNamespace = "http://puntersouthall.com/webservice/alfresco/", className = "com.puntersouthall.webservice.alfresco.GetRecentTasksForMember")
    @ResponseWrapper(localName = "GetRecentTasksForMemberResponse", targetNamespace = "http://puntersouthall.com/webservice/alfresco/", className = "com.puntersouthall.webservice.alfresco.GetRecentTasksForMemberResponse")
    public ArrayOfRecentTasksReturnType getRecentTasksForMember(
            @WebParam(name = "centralMemberRecordID", targetNamespace = "http://puntersouthall.com/webservice/alfresco/")
                    Integer centralMemberRecordID,
            @WebParam(name = "databaseMemberID", targetNamespace = "http://puntersouthall.com/webservice/alfresco/")
                    Integer databaseMemberID,
            @WebParam(name = "recordsToReturn", targetNamespace = "http://puntersouthall.com/webservice/alfresco/")
                    Integer recordsToReturn,
            @WebParam(name = "returnAllRecords", targetNamespace = "http://puntersouthall.com/webservice/alfresco/")
                    Boolean returnAllRecords);

}
